### ISSUE TITLE
혼자 코딩 하는 상황이면 리팩토링 우선으로 해볼것

### ISSUE THREAD

**Issue by chanwoong1** [seokunee/miniRT_42#28]
코드가 살짝 더러울 수 있으니, 리펙토링을 우선으로 해보는것이 좋을것 같아요. 만나서 같이 기능 구현 하는게 확실히 빠른것같아서요.

여기 이슈에서 브랜치 만들어서 해주세용

**Comment by get6** [comment]
일단 develop(0e70ea42b0f6ddd0bb6005a6f0e0b3d443dc1e5a)에서 어느정도 작업했어요~ 여기서 브랜치 나눠주세여!
